
############################################################
#
# This file supports the following use-case:
# - local development
#     `docker-compose --file ./docker-compose.yml up frontend --build`
#     The React frontend is built but for each change
#     everything must be restarted.
#     TODO: make changes cause live-reload.
#
# Useful commands:
#
#   Stop all containers: `docker stop $(docker ps -a -q)`
#
############################################################

version: "2.1"
services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
    - "3000:3000"

  e2e-test-runner:
    # https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command
    image: cypress/included:13.6.6
    depends_on:
      frontend:
        condition: service_healthy
    environment:
    - CYPRESS_baseUrl=http://frontend:3000
    working_dir: /e2e
    volumes:
    - ./packages/cypress:/e2e
    links:
    - frontend
